<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit.v3" Version="4.0.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    <ProjectReference Include="../../src/Restoration.Core/Restoration.Core.csproj" />
    <ProjectReference Include="../../src/Restoration.Game/Restoration.Game.csproj" />
    <ProjectReference Include="../../src/Restoration.Extractor/Restoration.Extractor.csproj" />
    <ProjectReference Include="../../src/Restoration.Resources/Restoration.Resources.csproj" />
  </ItemGroup>
</Project>
