<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.12" />
    <ProjectReference Include="../../src/Restoration.Resources/Restoration.Resources.csproj" />
  </ItemGroup>
</Project>
